from pymongo import MongoClient
from patient_data import *
from provider_data import *

# establish connection to MongoDB
MONGO_DB_URL = "mongodb://127.0.0.1:27017"
client = MongoClient(MONGO_DB_URL)

# TODO: old?
# connect to webex_instant_connect db
instant_connect_db = client["webex_instant_connect"]

# initialize patient collection
patient_collection = instant_connect_db["patients"]
patient_collection.insert_many(patients)

# initialize provider collection
provider_collection = instant_connect_db["providers"]
provider_collection.insert_many(providers)

# initialize appointment collection
# this will be done when the first appointment is generated by instant connect